language: python
python:
  - "2.7"
services: mongodb
# command to install dependencies
install: "pip install -r requirements.txt"
# # command to run tests
script: nosetests --with-coverage pymongo-job-queue
after_success: codecov
